apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: devopsapp1-updater
  namespace: argocd
spec:
  applicationRefs:
  - namePattern: devopsapp1
    images:
    - alias: devopsapp1
      imageName: sar0j/devopsapp1
      commonUpdateSettings:
        updateStrategy: newest-build
        forceUpdate: true
      manifestTargets:
        helm:
          name: image.repository
          tag: image.tag