apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devopsapp1-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: devopsapp1
  endpoints:
  - port: http
    path: /metrics
    interval: 15s